apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: backend-allow-gateway-sa
spec:
  selector:
    matchLabels:
      app: backend
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/platform/sa/api-gateway
